title: "Yuchen Han"
author: "yuchen"
description: "University of Colorado Anschutz"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true    # show site description and social links in footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title: "Home Change", icon:home}
  - {file: "README.md", title: "About me", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yuchenhan2020@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/yuchenh07"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/yuchenhan2020"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
